### ISSUE TITLE
Cygwinのrsyncでフォルダ同期をさせる方法

### ISSUE THREAD

**Issue by s-tomura** [sakama/vagrant-niftycloud#7]
※ 2/28 　2/27に転記したコードが間違ってましたので差し替えました。すみません。
　　　　　SSHのPrivate Keyのパス名の変更部分がありませんでした。

プラグインそのままではrsyncによるフォルダ同期が成功せず、そのあとのプロビジョニングまで到達しませんでした。
環境：　Windows10 , Windows8.1

Git for Windowsをインストールしているので、Cygwinのrsyncとsshだけをインストールしてトライしましたが、これも失敗。

どうやらWindows側のパス名のドライブ名付近がNGらしく、プラグイン側を改訂したら同期できるようになりました。

変更前のパス名：D:/vagrant/niftycloud
変更後のパス名：/cygdrive/D/vagrant/niftycloud

「D:」を「/cygdrive/D/」に変更したらOKでした。
尚、プラグインの「sync_folders.rb」を改訂しましたが、SSHのPrivate Keyのパス名も同様に変更する必要がありました。

～/gems/vagrant-niftycloud-0.3.0/lib/vagrant-niftycloud/action/sync_folders.rb

あちこち変更したので、変更後の内容を以下に転記します。
VagrantをWindowsで動かす場合のみを考慮してます。他のOSでは動作しないと思います。
自分はRubyの使い手ではないので、あちこちググって動くようにしただけなので、ご了承ください。

---
```ruby
# -*- coding: utf-8 -*-
require "log4r"

require "vagrant/util/subprocess"

module VagrantPlugins
  module NiftyCloud
    module Action
      # This middleware uses `rsync` to sync the folders over to the
      # NiftyCloud instance.
      class SyncFolders
        def initialize(app, env)
          @app    = app
          @logger = Log4r::Logger.new("vagrant_niftycloud::action::sync_folders")
        end

        def call(env)
          @app.call(env)

          ssh_info = env[:machine].ssh_info
          env[:machine].config.vm.synced_folders.each do |id, data|
            begin
              # Ignore disabled shared folders
              next if data[:disabled]

              hpath  = File.expand_path(data[:hostpath], env[:root_path])      # 追加
 	      hostpath  = hpath.gsub(/\A(\w):/,'/cygdrive/\1')                        # 変更
              guestpath = data[:guestpath]
              private_key_paths = ssh_info[:private_key_path]                        # 変更
              private_key_path = private_key_paths[0].gsub(/\A(\w):/,'/cygdrive/\1')  #追加

              # Make sure there is a trailing slash on the host path to
              # avoid creating an additional directory with rsync
              hostpath = "#{hostpath}/" if hostpath !~ /\/$/

              env[:ui].info(I18n.t("vagrant_niftycloud.rsync_folder",
                                  :hostpath => hostpath,
                                  :guestpath => guestpath))

              # Create the guest path
              env[:machine].communicate.sudo("mkdir -p '#{guestpath}'")
              env[:machine].communicate.sudo(
                "chown #{ssh_info[:username]} '#{guestpath}'")

              # Rsync over to the guest path using the SSH info
              command = [
                "rsync", "--verbose", "--archive", "-z", "--delete", "--copy-links",  "--exclude", ".vagrant/", 　　
                "-e", "ssh -p #{ssh_info[:port]} -o StrictHostKeyChecking=no -i '#{private_key_path}'",
                hostpath,
                "#{ssh_info[:username]}@#{ssh_info[:host]}:#{guestpath}"]    # 変更

              r = Vagrant::Util::Subprocess.execute(*command)
              if r.exit_code != 0
                raise Errors::RsyncError,
                  :guestpath => guestpath,
                  :hostpath => hostpath,
                  :stderr => r.stderr
              end
            rescue => e
              raise Errors::RsyncError,
                :guestpath => guestpath,
                :hostpath => hostpath,
                :stderr => e.message
            end
          end
        end
      end
    end
  end
end

```

**Comment by s-tomura** [comment]
WindowsでVagrantを実行する場合のみ、フォルダ同期とSSHキーのパス名を調整するようにしてみました。
Windowsにはrsyncが無いので、Cygwinのrsyncがインストールされている必要があります。

フォルダ同期時の不要なオプションを削除し、元のコードとの変更部分を最小限にしてみました。
rsync_folders.rb変更版の内容は以下の通りです。
```
# -*- coding: utf-8 -*-
require "log4r"

require "vagrant/util/subprocess"

module VagrantPlugins
  module NiftyCloud
    module Action
      # This middleware uses `rsync` to sync the folders over to the
      # NiftyCloud instance.
      class SyncFolders
        def initialize(app, env)
          @app    = app
          @logger = Log4r::Logger.new("vagrant_niftycloud::action::sync_folders")
        end

        def call(env)
          @app.call(env)

          ssh_info = env[:machine].ssh_info
          env[:machine].config.vm.synced_folders.each do |id, data|
            begin
              # Ignore disabled shared folders
              next if data[:disabled]

              hostpath  = File.expand_path(data[:hostpath], env[:root_path])
              guestpath = data[:guestpath]
              # 下記5行が追加した行です。 
              private_key_paths = ssh_info[:private_key_path]
              if Vagrant::Util::Platform.windows?
                hostpath  = hostpath.gsub(/\A(\w):/,'/cygdrive/\1')
                private_key_path = private_key_paths[0].gsub(/\A(\w):/,'/cygdrive/\1')
              end

              # Make sure there is a trailing slash on the host path to
              # avoid creating an additional directory with rsync
              hostpath = "#{hostpath}/" if hostpath !~ /\/$/

              env[:ui].info(I18n.t("vagrant_niftycloud.rsync_folder",
                                  :hostpath => hostpath,
                                  :guestpath => guestpath))

              # Create the guest path
              env[:machine].communicate.sudo("mkdir -p '#{guestpath}'")
              env[:machine].communicate.sudo(
                "chown #{ssh_info[:username]} '#{guestpath}'")

              # Rsync over to the guest path using the SSH info
              command = [
                "rsync", "--verbose", "--archive", "-z", 
                "--exclude", ".vagrant/", "--exclude", ".git/",
                "-e", "ssh -p #{ssh_info[:port]} -o StrictHostKeyChecking=no -i '#{private_key_path}'",
                hostpath,
                "#{ssh_info[:username]}@#{ssh_info[:host]}:#{guestpath}"]
              # 上記52行目が変更した行です

              r = Vagrant::Util::Subprocess.execute(*command)
              if r.exit_code != 0
                raise Errors::RsyncError,
                  :guestpath => guestpath,
                  :hostpath => hostpath,
                  :stderr => r.stderr
              end
            rescue => e
              raise Errors::RsyncError,
                :guestpath => guestpath,
                :hostpath => hostpath,
                :stderr => e.message
            end
          end
        end
      end
    end
  end
end

```

**Comment by sakama** [comment]
@s-tomura ありがとうございます。
こちらVagrantfile内の `config.vm.synced_folder` と `config.ssh.private_key_path` で設定できたりしませんかね？
以下細かいパス指定は違うかもしれませんがどうでしょう？
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.synced_folder "/cygdrive/D/vagrant/niftycloud" # synced_folderの設定
  config.ssh.private_key_path = "/cygdrive/D/vagrant/niftycloud" # private_key_pathの設定

  config.vm.provider :niftycloud do |niftycloud, override|
    niftycloud.access_key_id = ENV["NIFTY_CLOUD_ACCESS_KEY"] || "<Your Access Key ID>"
    ...
  end
end
```

* `config.vm.synced_folder`
  [Basic Usage - Synced Folders - Vagrant by HashiCorp](https://www.vagrantup.com/docs/synced-folders/basic_usage.html)
  [Vagrant | synced_folder でホストOSとゲストOSの任意のフォルダを同期する - Qiita](https://qiita.com/tbpgr/items/67125ea883409ae5fd51)

* `config.ssh.private_key_path`
  [config.ssh - Vagrantfile - Vagrant by HashiCorp](https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html)

Vagrantfile内で設定できるのであれば、READMEをアップデートしてWindowsについての記述を追加しようと思います。
設定できないということであればコードを変更したいと思います。

**Comment by s-tomura** [comment]
sakuma さん、ありがとうございます。

Vagrantfileの設定を変えてトライしてみました。
結果は、エラーでサーバ生成できませんでした。
Win10のPowerShellでrsyncがあるかどうか確認してみましたが、試した範囲ではrsyncコマンドは無いようです。
そうするとWindowsの場合、何のrsync.exeをインストールするかでパス名のフォーマットも違う可能性があります。
ハードコードを回避できる代案を探してみたいと思います。

トライした環境は以下の通りです。
- OSはWindows8.1
- コマンド実行環境は３種類
  - コマンドプロンプト ( cygwinにパスが通っていて、rsyncが実行可能)
  - Git for WindowsのBash (MinGWのシェルだからか、rsyncをコマンドで実行しようとしてもエラー）
  - PowerShell (Windows8.1標準？：cygwinにパスが通っているので参考にならないかも知れません)

### 設定内容（vagrantfile）
``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.synced_folder "/cygdrive/D/Vagrant/niftycloud" , "/vagrant"
  config.ssh.private_key_path = "/cygdrive/D/Vagrant/niftycloud/vagrant_authokeys/id_rsa"
  config.vm.provider :niftycloud do |niftycloud, override|
    niftycloud.access_key_id = ENV["NIFTY_CLOUD_ACCESS_KEY"] || "---"
    :
  end
:
end  
```

### テスト結果
サーバ作成段階でエラー
#### コマンドプロンプトの場合
```
D:\Vagrant\niftycloud>vagrant up --no-provision
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* `private_key_path` file must exist: /cygdrive/D/Vagrant/niftycloud/vagrant_authokeys/id_rsa

vm:
* The host path of the shared folder is missing: /cygdrive/D/Vagrant/niftycloud
```
#### PowerShell (Win8.1) の場合
結果は同じ
```
PS D:\vagrant\niftycloud> vagrant up --no-provision
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* `private_key_path` file must exist: /cygdrive/D/Vagrant/niftycloud/vagrant_authokeys/id_rsa

vm:
* The host path of the shared folder is missing: /cygdrive/D/Vagrant/niftycloud
```
### Git for Windows のBash (MinGW64)
```
$ vagrant up --no-provision
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* `private_key_path` file must exist: /cygdrive/D/Vagrant/niftycloud/vagrant_authokeys/id_rsa

vm:
* The host path of the shared folder is missing: /cygdrive/D/Vagrant/niftycloud
```

### 参考
”cygdrive/d/"の代わりに”D:/”を使うとサーバ作成までは成功します。
しかし、プロビジョニングでエラーになります。

**Comment by sakama** [comment]
検証ありがとうございます。
このプラグインは[vagrant-aws](https://github.com/mitchellh/vagrant-aws/) をfolkして作っているんですが、vagrant-niftycloudのリリース以来vagrant-awsへの変更の追随はしていないんですよね。
元のコードはもしかするとその辺対応済みかもしれないので、何かしらヒントはあるかもしれませんね。

**Comment by s-tomura** [comment]
いろいろ試してみたのですが、vagrantfile内の定義のみで解決する方法は現在まだ見つかっておりません。
vagrantfile内で"/cygdrive/d/～"と記述すると、vagrant upすらエラーになりサーバ生成できません。

結果的には、vagrantfile内で"/cygdrive/(ドライブ名)/～" を定義するとサーバ生成もプロビジョニングもエラーになります。

試しに"D:/～"にするとvagrant upでサーバ生成が開始されますが、Rsyncでフォルダ同期する箇所でエラーになります。（サーバは生成されます）

試しにサーバが生成された後でvagrantfileを以下のように編集し、vagrant provisionを実行してみました。結果はエラーメッセージが表示されてだけでした。
 -  "D:/～"　を　"/cygdrive/d/～"　変更

そこで代案を考えてみました。
## 代案）Windows＆Cygwinの場合だけ「sync_folders.rb」内でパス名を調整する
というのはいかがでしょうか？
ハードコーディングにはなりますが、条件を絞り込むことで他の環境への影響を最小限にする案です。

Cygwinの判定方法は、環境変数「TERM」の内容が「cygwin」かどうかで判断できるのではと考えました。
環境変数「TERM」は、コマンドプロンプト、Win8.1のPS、Git for Windowsに含まれているMinGW64のターミナルの全てにおいて存在と内容を確認できました。

この環境変数が存在し、且つ内容が「cygwin」なら、cygwinがインストールされた環境だと判断できるのではと考えた次第です。
Rubyの使い手ではないので、可能かどうかも、具体的なコードも分からず、愚策かも知れないのに提案するのは失礼かも知れませんが、ご容赦ください。
この案、いかがでしょうか？

**Comment by s-tomura** [comment]
お手数をお掛けしてすみません。
条件の絞り込みに環境変数「TERM」は不適でした。
申し訳ございません。

下記のようにパス名の編集する条件を絞り込んだのですが、PowerShellとコマンドプロンプトがNGでした。
**NG**
```Ruby
            :
              if Vagrant::Util::Platform.windows? and ENV['TERM']== "cygwin"
                hostpath  = hostpath.gsub(/\A(\w):/,'/cygdrive/\1')
                private_key_path = private_key_path.gsub(/\A(\w):/,'/cygdrive/\1')
              end
           :
```

トライした結果、環境変数「PATH」に文字列「cygwin」が含まれているかどうかで絞り込むと、コマンドプロンプト、PowerShell、MinGWのBashシェルのいずれもvagrant upコマンドがエラーなしで実行できました。
変更後の内容は以下の通りです。
**OK**
```Ruby
             :
             if Vagrant::Util::Platform.windows? and ENV['PATH'].include?("cygwin")
                hostpath  = hostpath.gsub(/\A(\w):/,'/cygdrive/\1')
                private_key_path = private_key_path.gsub(/\A(\w):/,'/cygdrive/\1')
              end
             :
```
Windows環境で、且つCygwinがインストールされている場合のみ、パス名の先頭を変更するようにしてみました。
Rsyncをインストールしているかどうかはチェックしておりません。
実は他力本願では申し訳ないと思い、挑戦してみました。

vagrant-awsプラグインの変更内容を追随することで解決できればうれしい限りです。
お手数をお掛けしてすみません。

**Comment by sakama** [comment]
ありがとうございます！
私の方でもチェックしてみますね。

**Comment by sakama** [comment]
#12 で修正して[0.4.0](https://rubygems.org/gems/vagrant-niftycloud/versions/0.4.0) をリリースしました。
これでご確認頂けますか？問題なさそうであればこのIssueをクローズ頂ければと思います。

**Comment by stomura6** [comment]
リリースありがとうございます。
動作確認してみました。
#### 結果

1. vagrant upは、"--no-provision" オプションをつけて実行するとサーバが生成されました。
    そのあとで vagrant provision を実行すると正常に動作してくれました。
　以下の３つで動作することを確認しました。
　　①コマンドプロンプト＋cygwin
　　②Git for Windowsに付属のMinGW64のターミナル＋Cygwin
　　③Win8.1 PowerShell＋cygwin

```sh
 $ vagrant up  --provider niftycloud --no-provision
```

2. "--no-provision" オプションをつけずにvagrant upを実行するとProvisioning時にエラーが発生します。生成されたサーバは自動的に削除されてしまいました。
私としては、上記１．で十分なので問題ありません。
私のスキルでは解決策を見つけることはかなり困難ですので、制限事項としていただくだけで十分です。

参考までに、エラーメッセージは以下の通りです。
```sh
==> master: Rsyncing folder: /cygdrive/D/Vagrant/niftycloud/ => /vagrant
==> master: Running provisioner: ansible_local...
==> master: Terminating the instance...
==> master: Waiting for instance to become "stopped"...
d:/Vagrant/.vagrant.d/gems/2.4.3/gems/vagrant-niftycloud-0.4.0/lib/vagrant-niftycloud/action/timed_provision.rb:9:in `run_provisioner': wrong number of arguments (given 1, expected 3) (ArgumentError)
```
何故か、vagrant up の時にエラーとなります。
一度サーバを作成してから vagrant provision を実行するときは何もエラーが出ません。

もし解決されれば嬉しい限りですが、Provisioningが動作するようになっただけでも感謝です。
ありがとうございました。

**Comment by sakama** [comment]
恐らく使ってらっしゃるVagrantfileは `config.vm.provision... end` のブロックがないものですかね？
例： https://github.com/sakama/vagrant-niftycloud/blob/master/Vagrantfile.chef.sample#L20-L30
だとしたらこのブロックがない且つ `--no-provision`を指定せずに実行した場合、恐らくAnsibleによるProvisioningが走るのがデフォルトの動作で、ただブロックの指定がないためにProvisioningが実行できずにサーバをストップして処理を終えているように見えます。

私もChef以外での動作は確認していないので、上記が原因であれば一旦問題ないかと思います。

**Comment by stomura6** [comment]
アドバイスありがとうございます。
一応 `config.vm.provision... end` はあるのですが、ご紹介いただいたchefでのサンプルとは位置が違ってました。
念のため、`config.vm.provision... end` を **`config.vm.provider... end`** のブロック内に移動してみたりしたのですが、結果は変わりませんでした。
provisioner として `ansible_local` を使っていることが原因かも知れません。
サーバ生成とプロビジョニングを分けて行えば問題ないので、クローズ致します。
ありがとうございました。
