### ISSUE TITLE
ニフクラのサーバータイプ Type-eの対応

### ISSUE THREAD

**Issue by s-tomura** [sakama/vagrant-niftycloud#8]
安価なType-eのサーバを作成できるようにプラグインを変更しました。

対象ファイルは以下の通り。
～/gems/nifty-cloud-sdk-1.7/lib/NIFTY/Cloud/instances.rb

変更したのは、INSTANCE_TYPEの設定するところです。
変更後の内容は以下の通り
```
      INSTANCE_TYPE                 = ['mini', 'small', 'small2', 'small4', 'small8', 'small16', 'medium', 'medium4', 'medium8', 'medium16', 'medium24', 'large', 'large8', 'large16', 'large24', 'large32','e-mini', 'e-small', 'e-small2', 'e-small4', 'e-small8' , 'e-small16', 'e-medium', 'e-medium4', 'e-medium8', 'e-medium16', 'e-medium24', 'e-large', 'e-large8', 'e-large16', 'e-large24', 'e-large32']
```
若干、Type-hも追加してます。
尚、Type-eのe-xlargeシリーズ以降、Type-hのxlargeシリーズ以降は追加しておりません。

**Comment by sakama** [comment]
こちらは [ニフティクラウド SDK for Ruby](https://github.com/nifcloud/sdk-ruby)内で定義されている部分ですね。
https://github.com/nifcloud/sdk-ruby/blob/v1.11.0.beta6/lib/NIFTY/Cloud/instances.rb#L4

SDK for Rubyのバージョンが低かったので最新のバージョンにアップデートします。 #8

**Comment by sakama** [comment]
@s-tomura 挙げて頂いたリストのうちsmall16, e-small16はSDKにまだ入っていないようなので対応できなそうです。
逆に以下のサーバタイプはSDK内で定義されているので入ります。
```
'extra-large16', 'extra-large24', 'extra-large32', 'double-large32', 'double-large48', 'double-large64', 'double-large96'
```

**Comment by s-tomura** [comment]
sakuma さん、ありがとうございます。
small16とe-small16の件は、了解しました。

**Comment by sakama** [comment]
[0.4.0](https://rubygems.org/gems/vagrant-niftycloud/versions/0.4.0) にて修正。
クローズします。

**Comment by stomura6** [comment]
ありがとうございます。
テストしてみたところ、sdkのlib/NIFTY.rbの60行目で以下のようなワーニングが出ました。

```
d:/Vagrant/.vagrant.d/gems/2.4.3/gems/nifty-cloud-sdk-1.11.beta7/lib/NIFTY.rb:60: warning: constant OpenSSL::Digest::Digest is deprecated
```
以下のように変更するとワーニングが出なくなりました。
変更前（60行目）
```Ruby
    digest = OpenSSL::Digest::Digest.new(key_type)
```
変更後
```Ruby
    digest = OpenSSL::Digest.new(key_type)
```
それ以外は問題ありません。
一応、ご報告致します。

**Comment by sakama** [comment]
これはNifty Cloud SDK内部で発生しているwarningですね。
deprecatedになった呼び出し方法に対するwarningなので当分問題ないかと思いますが、本家の方にIssue上げると良いのではないかと思います。
https://github.com/nifcloud/sdk-ruby

**Comment by sakama** [comment]
既にNifty Cloud SDKの方に修正するPR上がってました。
https://github.com/nifcloud/sdk-ruby/pull/27/files

今の進捗状況がわかりませんが、こちらにコメントすると進むかもしれません。

**Comment by stomura6** [comment]
アドバイスいただき、ありがとうございます。
この件は、修正されるのを気長に待つことに致します。
お陰様で、「プルリクエスト」というものの理解が少し進みました。
良く分からなかったもので。
ありがとうございました。
